apiVersion: apps/v1
kind: Deployment 
metadata:
  name: telegraf-deployment
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
     matchLabels:
       app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: telegraf_image
        imagePullPolicy: Never
        volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
        ports:
          - containerPort: 8086
      volumes:
      - name: docker-socket
        hostPath:
            path: /var/run/docker.sock
            type: Socket 